#!/bin/bash
function minigame0 { minexit=false; until [[ $minexit = true ]]; do clear
	echo -e "Welcome to mini game 1, to play you must type le as fast as you can"'!'"\nPress any key to begin"
	read -s -n 1 input; echo " " > ~/Desktop/lele; echo "0" > ~/Desktop/lecount
		lecount=0; timer=60; while [[ $timer -gt 0 ]]; do
			let timer=$timer-1; echo $timer > ~/Desktop/timer
			sleep 1
		done& while [[ $timer -gt 0 ]]; do clear
			timer=$(cat ~/Desktop/timer); lecount=$(cat ~/Desktop/lecount)
			echo -e "Time: $timer\nLe Count: $lecount"
				for i in $(cat ~/Desktop/lele); do echo -n "$i"; done; sleep 0.1
		done& while [[ $(cat ~/Desktop/timer) -gt  0 ]]; do
			read -s -n 2 le
				if [[ $le = le ]] || [[ $le = el ]]; then
					let lecount=$lecount+1; echo $lecount > ~/Desktop/lecount; echo le >> ~/Desktop/lele
				fi
		done
	lecount=$(cat ~/Desktop/lecount); rm ~/Desktop/lecount ~/Desktop/timer ~/Desktop/lele; clear
	echo "Your Score is $lecount"; minexit=true
done
}
function minigame1 { minexit=false; until [[ $minexit = true ]]; do clear
	echo -e "Welcome to mini game 2, to play you must shoot the le warrior\nPress any key to begin"
	read -s -n 1 add; echo 4 >> ~/Desktop/lewarrior; echo 2 >> ~/Desktop/warrior; echo true > ~/Desktop/lewar; warrior=2
		while [[ $(cat ~/Desktop/lewar) = true ]]; do
			sleep 1; var=$((RANDOM%3))
				if [[ $var = 0 ]]; then echo 4 > ~/Desktop/lewarrior
				elif [[ $var = 1 ]]; then echo 5 > ~/Desktop/lewarrior
				elif [[ $var = 2 ]]; then echo 6 > ~/Desktop/lewarrior; fi
		done& while [[ $(cat ~/Desktop/lewar) = true ]]; do clear
			lewarrior=$(cat ~/Desktop/lewarrior); warrior=$(cat ~/Desktop/warrior); laser=$(cat ~/Desktop/laser); m4="LE"; m5="  "; m6="  "; m1="  "; m2="LE"; m3="  "
				if [[ $lewarrior = 4 ]]; then m4="LE"; m5="  "; m6="  "
				elif [[ $lewarrior = 5 ]]; then m4="  "; m5="LE"; m6="  "
				elif [[ $lewarrior = 6 ]]; then m4="  "; m5="  "; m6="LE"; fi
				if [[ $warrior = 1 ]]; then m1="LE"; m2="  "; m3="  "
				elif [[ $warrior = 2 ]]; then m1="  "; m2="LE"; m3="  "
				elif [[ $warrior = 3 ]]; then m1="  "; m2="  "; m3="LE"; fi
				if [[ $laser = 1 ]]; then l1="||"; l2="  "; l3="  "; elif [[ $laser = 2 ]]; then l2="||"; l1="  "; l3="  "; elif [[ $laser = 3 ]]; then l3="||"; l2="  "; l1="  "; else l1="  "; l2="  "; l3="  "; fi
				if [[ $lewarrior = 4 ]] && [[ $laser = 1 ]]; then m4="XX"; elif [[ $lewarrior = 5 ]] && [[ $laser = 2 ]]; then m5="XX"; elif [[ $lewarrior = 6 ]] && [[ $laser = 3 ]]; then m6="XX"; fi
			echo "+----+----+----+"
			echo "| $m4   $m5   $m6 |  A and D to move,"
			echo "| $l1   $l2   $l3 |  space to shoot"
			echo "| $l1   $l2   $l3 |"
			echo "| $l1   $l2   $l3 |"
			echo "| $m1   $m2   $m3 |"
			echo "+--------------+"
			echo 0 > ~/Desktop/laser
			sleep 0.1
			if [[ $m4 = XX ]] || [[ $m5 = XX ]] || [[ $m6 = XX ]]; then echo false > ~/Desktop/lewar; fi
		done& while [[ 	$(cat ~/Desktop/lewar) = true ]]; do
			read -s -n 1 lmove
				if [[ $(echo "$lmove"a) = a ]]; then
					echo $warrior > ~/Desktop/laser
				elif [[ $lmove = a ]]; then
					let warrior=$warrior-1; if [[ $warrior -gt 3 ]]; then warrior=3; fi; echo $warrior > ~/Desktop/warrior
				elif [[ $lmove = d ]]; then
					let warrior=$warrior+1; if [[ $warrior -lt 1 ]]; then warrior=3; fi; echo $warrior > ~/Desktop/warrior
				fi
		done
		minexit=true
done
rm ~/Desktop/lewarrior ~/Desktop/lewar ~/Desktop/warrior ~/Desktop/laser;
}
clear; echo -e "Welcome to le game\nPress space to start"'!'
input=test
until [[ $(echo "$input"a) = a ]]; do
	read -s -n 1 input
done
minigame$((RANDOM%2))