#!/bin/sh
apo="'"
while [[ ${1:0:1} = '-' ]]; do
	N=1; L=${#1}
		while [[ $N -lt $L ]]; do
				case ${1:$N:1} in
				'f') f=1 ;;
				'o') if [[ $N -ne $(($L-1)) || ! -n ${2} ]] ; then
				echo "No File Specified"
				exit 1
				fi
				out=${2}
				shift ;;
				*) echo "Usage [ -f script to obfuscate ]"
				exit 1 ;;
				esac
			N=$(($N+1))
		done
	shift
done
enc=`cat $out | base64`
echo '
#!/bin/sh
echo '$apo' '$enc''$apo' | base64 -D > ~/Desktop/._encrypted; chmod +x ~/Desktop/._encrypted
cd desktop && ./._encrypted && rm rf ~/Desktop/._encrypted' > $out"_obf"